name: CI-CD workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  verify:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Check format
        run: pnpm run format-detect
        
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    # - name: Install Playwright Browsers
    #   run: pnpm exec playwright install --with-deps

    - name: Create .env
      run: |
        echo "VITE_SERVER_LINK=${{ secrets.VITE_SERVER_LINK }}" >> .env
        echo "VITE_WS_SERVER=${{ secrets.VITE_WS_SERVER }}" >> .env

    - name: Test
      run: pnpm test

    # - name: Run Playwright tests
    #   run: pnpm pw-headless

    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 10
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [verify, test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build
        env:
          BASE_URL: /${{ github.event.repository.name }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build

    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    concurrency:
      group: github-pages
      cancel-in-progress: false
    permissions:
      id-token: write
      pages: write
      contents: write
      packages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
